### ISSUE TITLE
Investigate what needs to be done to replace LDAP

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/incore-services#116]
Research on below components:

### INCORE services

- [ ] #117 
- [ ] #118
- [ ] #120
- [ ] #119
- [ ] #121
- [ ] #122
- [ ] #123
- [ ] #124
- [ ] #125

### Keycloak
- [ ] [Look at how to enable "account approving process" in keycloak](https://github.com/IN-CORE/platform/issues/47)

### UI
- [ ] [Replace login page with keycloak login page with custom CSS](https://github.com/IN-CORE/incore-ui/issues/117)

### cron jobs  and dev scripts
- [ ] Usergroup sync to mongodb for allocation (https://github.com/IN-CORE/platform/issues/49)
- [ ] Maestro sync to postgres database (https://github.com/IN-CORE/platform/issues/50)
 
### mongo
- [ ] Need to make sure if allocation related information is connected to ldap (https://github.com/IN-CORE/platform/issues/51)

### helm chart
- [ ] Look at all ldap mentioning in the helm chart (https://github.com/IN-CORE/incore-helm/issues/59)
- [ ] Remove cronjob for usergroup sync to mongodb for allocation (https://github.com/IN-CORE/incore-helm/issues/58)
- [ ] Remove cronjob for maestro usersync (https://github.com/IN-CORE/incore-helm/issues/58)

### other pieces that directly talk to LDAP

**Comment by longshuicy** [comment]
The investigation part is done. Closing this task
