### ISSUE TITLE
Investigate what needs to be done to support for multi hazard fragility

### ISSUE THREAD

**Issue by navarroc** [IN-CORE/incore-services#126]
The hazardType field for a fragility is a string field; however, there is no way to indicate that the fragility is multi-hazard. The expectation is the hazardType is "earthquake", "flood", "tsunami", etc; however, if a fragility requires both earthquake and tsunami, there is no clear way to indicate this in this field as it's currently implemented in the service. Since the DFR3 Service uses the hazard type to validate the fragility parameters are correct for the hazard type, the fragility can't be stored unless hazardType can be flexible enough to handle multi hazard. 

This impacts storing the DFR3 fragility curve, the DFR3 mapping and the use of these in the building damage analysis. The issue is broken into the following tasks that need to be done:

### IN-CORE services
- [x] #127
- [x] #128
- [x] #129
- [x] #130

### pyIncore
- [x] Review building damage to support multiple hazards] (https://github.com/IN-CORE/pyincore/issues/336)
- [x] [Refactor building damage to support multiple hazards] (https://github.com/IN-CORE/pyincore/issues/337)
- [ ] [Update building damage to verify hazard input meets the requirements of the DFR3 mapping] (https://github.com/IN-CORE/pyincore/issues/338)

### UI
- [x] Add DFR3Viewer support for multi-hazard fragilities] (https://github.com/IN-CORE/incore-ui/issues/119)

**Comment by longshuicy** [comment]
Closing this as most subtasks have been addressed, except one. Track the remaining task in PyIncore.
